export const ADD_CATEGORY = 'ADD_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const CATEGORY_DATA_LOADED = 'CATEGORY_DATA_LOADED';

export const API_CALL_IN_PROGRESS = 'API_CALL_IN_PROGRESS';
export const API_CALL_SUCCESS = 'API_CALL_SUCCESS';
export const API_CALL_FAILED = 'API_CALL_FAILED';

export const INVALID_INPUT = 'INVALID_INPUT';
